apiVersion: v1
kind: Service
metadata:
  name: basicnodeserver-service
  labels:
    app: basicnodeserver
spec:
  type: LoadBalancer
  selector:
    app: basicnodeserver
  ports:
    - protocol: TCP
      name: http
      port: 9000
      targetPort: 9000